apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: subtitler-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: api.paranoids.org
      http:
        paths:
          - pathType: Prefix
            path: /subtitler-api(/|$)(.*)
            backend:
              service:
                name: subtitler-api-svc
                port:
                  number: 80
